#ifndef CONSTSANTS_H
#define CONSTSANTS_H

#define VERSION "1.1.4"

#define NUM_FIELDS_SHOWN_IN_MAIN_TABLE 3

#define PI 3.14159265
#define LuxToFootcandleRatio 0.09290304
//#define EmperialToMetricCoefficient 10.7631
#define FeetPerMeter 3.28

#define FIRST_FIXTURE 1
#define MAX_NUMBER_OF_FIXTURES 100
#define NUMOFDECIMALS 2
#define NUMOFDECIMALSLIGHTLEVELS 0
#define UNKNOWN "---"

#define STARTUP_DIALOG_SIZE 254,176
#define SAVE_AND_QUIT_SIZE 383, 98
#define FIXTURE_EDIT_SIZE_SMALL 350,400
#define FIXTURE_EDIT_SIZE_LARGE 650,400
#define EDIT_ALL_SIZE 400,360
#define CSV_DIALOG_SIZE 190,102
#define CONFIRM_FIXTURE_REMOVE_SIZE 295,96

#define DEFAULT_NAME "New Fixture"
#define DEFAULT_LUMENS 0
#define DEFAULT_CANDELA 0
#define DEFAULT_DIST_METERS 5
#define DEFAULT_DIST_FEET 32.8
#define DEFAULT_LUX 0
#define DEFAULT_FC 0
#define DEFAULT_F_ANGLE 0
#define DEFAULT_FIELD_SIZE_METERS 0
#define DEFAULT_FIELD_SIZE_FEET 0
#define DEFAULT_WATTAGE 0
#define DEFAULT_EFFICACY 0
#define DEFAULT_B_ANGLE 0
#define DEFAULT_BEAM_SIZE_METERS 0
#define DEFAULT_BEAM_SIZE_FEET 0
#define DEFAULT_COLORTEMP UNKNOWN
#define DEFAULT_CRI 0;
#define DEFAULT_LED_MIX UNKNOWN
#define DEFAULT_STREET_PRICE 0
#define DEFAULT_LIST_PRICE 0
#define DEFAULT_OTHER_INFO ""


#endif // CONSTSANTS_H

//QFileDialog::getSaveFileName(options..)
